apiVersion: apps.fedoraproject.org/v1alpha1
kind: MBKojiBuilder
metadata:
  name: mb-koji-builder
spec:
  image: quay.io/fedora/koji-builder:latest
  replicas: 1
  configmap: koji-builder-configmap
  cacert_secret: koji-hub-ca-cert
  client_cert_secret: koji-builder-client-cert
  koji_hub_user: 'koji-builder.mbox.dev'
  koji_hub_url: 'https://koji-hub:8443'
  max_jobs: 5
  vendor: MBox
  host_arch: x86
  host_name: koji-hub:8443
  ssl_verify: false
  shared_pvc: koji-hub-mnt-pvc
  # mbox: example-mbox #uncomment to retrieve pvc and cert config from a mbox cr
