apiVersion: apps.fedoraproject.org/v1alpha1
kind: MBKojiHub
metadata:
  name: mb-koji-hub
  labels:
    app: mb-koji-hub
spec:
  image: quay.io/fedora/koji-hub:latest
  replicas: 1
  persistent: true
  host: 'koji-hub'
  configmap: koji-hub
  ca_cert_secret: koji-hub-ca-cert
  service_cert_secret: koji-hub-service-cert
  postgres_secret: postgres
  http_enabled: true
  https_enabled: true
  topic_prefix: mbox_dev
  fedora_messaging_url: amqps://koji:something@rabbitmq
  messaging_cert_cm: koji-hub-msg
  ingress_backend: nginx
  httpd_pvc_name: koji-hub-httpd-pvc
  httpd_pvc_size: 1Gi
  mnt_pvc_name: koji-hub-mnt-pvc
  mnt_pvc_size: 10Gi
  # mbox: example-mbox #uncomment to retrieve pvc and cert config from a mbox cr
